DISTORTION_TYPES = ['crop', 'rotate', 'sheer', 'perspective', 'spherical', 'barrel', 'MRF', 'twirl']
DISTORTION_TYPES_NUM = len(DISTORTION_TYPES)
DISTORTION_LEVELS = 3
GROUP_NUM = 10
IMAGE_NUM = 20
REDUNDENT_NUM = 2
SOURCE_PER_GROUP = IMAGE_NUM/GROUP_NUM
IMAGE_PER_GROUP = SOURCE_PER_GROUP * DISTORTION_TYPES_NUM * DISTORTION_LEVELS + REDUNDENT_NUM
SHOW_TOTAL_NUM = SOURCE_PER_GROUP * DISTORTION_TYPES_NUM * DISTORTION_LEVELS + REDUNDENT_NUM

IMG_SERVER = 'flasksurvey.s3.amazonaws.com/'